// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: metrics.proto

// https://github.com/mgravell/protobuf-net
// https://protogensite.azurewebsites.net/
// change 232 line: add 'set'

// ReSharper disable All
#pragma warning disable CS1591, CS0612, CS3021

namespace Prometheus.Client.Contracts
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CLabelPair : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Value
        {
            get { return __pbn__Value ?? ""; }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private string __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CGauge : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public double Value
        {
            get { return __pbn__Value.GetValueOrDefault(); }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private double? __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CCounter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public double Value
        {
            get { return __pbn__Value.GetValueOrDefault(); }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private double? __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CQuantile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"quantile")]
        public double Quantile
        {
            get { return __pbn__quantile.GetValueOrDefault(); }
            set { __pbn__quantile = value; }
        }
        public bool ShouldSerializequantile() => __pbn__quantile != null;
        public void Resetquantile() => __pbn__quantile = null;
        private double? __pbn__quantile;

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public double Value
        {
            get { return __pbn__Value.GetValueOrDefault(); }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private double? __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CSummary : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sample_count")]
        public ulong SampleCount
        {
            get { return __pbn__SampleCount.GetValueOrDefault(); }
            set { __pbn__SampleCount = value; }
        }
        public bool ShouldSerializeSampleCount() => __pbn__SampleCount != null;
        public void ResetSampleCount() => __pbn__SampleCount = null;
        private ulong? __pbn__SampleCount;

        [global::ProtoBuf.ProtoMember(2, Name = @"sample_sum")]
        public double SampleSum
        {
            get { return __pbn__SampleSum.GetValueOrDefault(); }
            set { __pbn__SampleSum = value; }
        }
        public bool ShouldSerializeSampleSum() => __pbn__SampleSum != null;
        public void ResetSampleSum() => __pbn__SampleSum = null;
        private double? __pbn__SampleSum;

        [global::ProtoBuf.ProtoMember(3, Name = @"quantile")]
        public global::System.Collections.Generic.List<CQuantile> Quantiles { get; } = new global::System.Collections.Generic.List<CQuantile>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CUntyped : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value")]
        public double Value
        {
            get { return __pbn__Value.GetValueOrDefault(); }
            set { __pbn__Value = value; }
        }
        public bool ShouldSerializeValue() => __pbn__Value != null;
        public void ResetValue() => __pbn__Value = null;
        private double? __pbn__Value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CHistogram : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sample_count")]
        public ulong SampleCount
        {
            get { return __pbn__SampleCount.GetValueOrDefault(); }
            set { __pbn__SampleCount = value; }
        }
        public bool ShouldSerializeSampleCount() => __pbn__SampleCount != null;
        public void ResetSampleCount() => __pbn__SampleCount = null;
        private ulong? __pbn__SampleCount;

        [global::ProtoBuf.ProtoMember(2, Name = @"sample_sum")]
        public double SampleSum
        {
            get { return __pbn__SampleSum.GetValueOrDefault(); }
            set { __pbn__SampleSum = value; }
        }
        public bool ShouldSerializeSampleSum() => __pbn__SampleSum != null;
        public void ResetSampleSum() => __pbn__SampleSum = null;
        private double? __pbn__SampleSum;

        [global::ProtoBuf.ProtoMember(3, Name = @"bucket")]
        public global::System.Collections.Generic.List<CBucket> Buckets { get; } = new global::System.Collections.Generic.List<CBucket>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CBucket : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cumulative_count")]
        public ulong CumulativeCount
        {
            get { return __pbn__CumulativeCount.GetValueOrDefault(); }
            set { __pbn__CumulativeCount = value; }
        }
        public bool ShouldSerializeCumulativeCount() => __pbn__CumulativeCount != null;
        public void ResetCumulativeCount() => __pbn__CumulativeCount = null;
        private ulong? __pbn__CumulativeCount;

        [global::ProtoBuf.ProtoMember(2, Name = @"upper_bound")]
        public double UpperBound
        {
            get { return __pbn__UpperBound.GetValueOrDefault(); }
            set { __pbn__UpperBound = value; }
        }
        public bool ShouldSerializeUpperBound() => __pbn__UpperBound != null;
        public void ResetUpperBound() => __pbn__UpperBound = null;
        private double? __pbn__UpperBound;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CMetric : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"label")]
        public global::System.Collections.Generic.List<CLabelPair> Labels { get; set; } = new global::System.Collections.Generic.List<CLabelPair>();

        [global::ProtoBuf.ProtoMember(2, Name = @"gauge")]
        public CGauge CGauge { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"counter")]
        public CCounter CCounter { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"summary")]
        public CSummary CSummary { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"untyped")]
        public CUntyped CUntyped { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"histogram")]
        public CHistogram CHistogram { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"timestamp_ms")]
        public long TimestampMs
        {
            get { return __pbn__TimestampMs.GetValueOrDefault(); }
            set { __pbn__TimestampMs = value; }
        }
        public bool ShouldSerializeTimestampMs() => __pbn__TimestampMs != null;
        public void ResetTimestampMs() => __pbn__TimestampMs = null;
        private long? __pbn__TimestampMs;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CMetricFamily : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"help")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Help
        {
            get { return __pbn__Help ?? ""; }
            set { __pbn__Help = value; }
        }
        public bool ShouldSerializeHelp() => __pbn__Help != null;
        public void ResetHelp() => __pbn__Help = null;
        private string __pbn__Help;

        [global::ProtoBuf.ProtoMember(3, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(CMetricType.Counter)]
        public CMetricType Type
        {
            get { return __pbn__Type ?? CMetricType.Counter; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private CMetricType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(4, Name = @"metric")]
        public global::System.Collections.Generic.List<CMetric> Metrics { get; } = new global::System.Collections.Generic.List<CMetric>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum CMetricType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"COUNTER")]
        Counter = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"GAUGE")]
        Gauge = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"SUMMARY")]
        Summary = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"UNTYPED")]
        Untyped = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"HISTOGRAM")]
        Histogram = 4,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
